name: Create and publish Docker image

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assume deployer role for Testing
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::180466524585:role/github-role-Role-19FJ3ABJJ6OIN
          aws-region: eu-west-2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: CDK install
        run: npm install -g aws-cdk@2.29.1

      - name: NPM install
        run: npm ci

      - name: CDK deploy
        run: cdk deploy --require-approval never
