name: Create and publish Docker image

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  # See https://github.com/actions/runner/issues/691 for why this is required.
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  deploy:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/a-h/aws-go-cdk-action:main
      options: --user ${{ needs.configure.outputs.uid_gid }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assume deployer role for Testing
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::180466524585:role/github-role-Role-19FJ3ABJJ6OIN
          aws-region: eu-west-2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: NPM install
        run: npm ci

      - name: CDK deploy
        run: cdk deploy --require-approval never
